import type { Quiz } from '@/lib/types/quiz'

export const quiz: Quiz = {
  id: 'purification',
  lessonSlug: 'purification',
  title: 'Purification Questions',
  sections: [
    {
      title: 'Wudu and Purification Questions',
      questions: [
        {
          id: 'purification-q1',
          number: 1,
          text: 'How many conditions does ablution have?',
          type: 'multiple-choice',
          options: ['9', '10', '8'],
          correctIndex: 1,
        },
        {
          id: 'purification-q2',
          number: 2,
          text: 'The obligations of ablution are:',
          type: 'multiple-choice',
          options: [
            'The four limbs',
            'That which has preceded along with the order and continuity.',
          ],
          correctIndex: 1,
        },
        {
          id: 'purification-q3',
          number: 3,
          text: 'How many nullifiers does ablution have?',
          type: 'multiple-choice',
          options: ['6', '5', '8'],
          correctIndex: 2,
        },
        {
          id: 'purification-q4',
          number: 4,
          text: 'Choose the nullifiers of ablution from the following:',
          type: 'multiple-select',
          options: [
            'Camel meat',
            'Gazelle meat',
            'Stomach noise',
            'Gas',
            'Sleeping',
            'Washing a dead person',
            'Touching a woman',
          ],
          correctIndices: [0, 3, 4, 5],
        },
        {
          id: 'purification-q5',
          number: 5,
          text: 'Describe the Dry Ablution/ Tayamum:',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'purification-q6',
          number: 6,
          text: 'Describe the Islamic Shower:',
          type: 'fill-blank',
          isTextarea: true,
        },
      ],
    },
    {
      title: 'Rulings on Ablution',
      questions: [
        {
          id: 'purification-q7',
          number: 7,
          text: 'Mention the ruling of the following topic: Saying the intention out loud.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q8',
          number: 8,
          text: 'Mention the ruling of the following topic: Has intended to make ablution for 1 prayer then s/he prayed more than 1.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q9',
          number: 9,
          text: 'Mention the ruling of the following topic: Made ablution to read the Qur\'an then prayed.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q10',
          number: 10,
          text: 'Mention the ruling of the following topic: Discontinued the intention while making ablution.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q11',
          number: 11,
          text: 'Mention the ruling of the following topic: Discontinued the intention after making ablution.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q12',
          number: 12,
          text: 'Mention the ruling of the following topic: Made ablution and on the calf there is dough.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q13',
          number: 13,
          text: 'Mention the ruling of the following topic: Made ablution while eating camel meat.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q14',
          number: 14,
          text: 'Mention the ruling of the following topic: Made ablution with stolen water.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q15',
          number: 15,
          text: 'Mention the ruling of the following topic: Made ablution before cleaning private parts.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q16',
          number: 16,
          text: 'Mention the ruling of the following topic: Taking new water for the ears.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q17',
          number: 17,
          text: 'Mention the ruling of the following topic: Wiping the head three times.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q18',
          number: 18,
          text: 'Mention the ruling of the following topic: Washing every part once during ablution.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q19',
          number: 19,
          text: 'Mention the ruling of the following topic: Washing the parts three times each during ablution.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q20',
          number: 20,
          text: 'Mention the ruling of the following topic: Washing the hands during ablution.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q21',
          number: 21,
          text: 'Mention the ruling of the following topic: Running wet fingers through the beard.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q22',
          number: 22,
          text: 'Mention the ruling of the following topic: Rubbing the body parts during ablution.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q23',
          number: 23,
          text: 'Mention the ruling of the following topic: Wiping that which is obligatory to wash.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q24',
          number: 24,
          text: 'Mention the ruling of the following topic: Washing the hair.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q25',
          number: 25,
          text: 'Mention the ruling of the following topic: Entering the hands in the water container.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q26',
          number: 26,
          text: 'Mention the ruling of the following topic: Beginning with the right side during ablution.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q27',
          number: 27,
          text: 'Mention the ruling of the following topic: Washing the ablution parts more than three times.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q28',
          number: 28,
          text: 'Mention the ruling of the following topic: Washing the calf.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q29',
          number: 29,
          text: 'Mention the ruling of the following topic: Prayed after swimming without prior ablution.',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'purification-q30',
          number: 30,
          text: 'Mention the ruling of the following topic: Prayed after taking a shower and did not do ablution.',
          type: 'fill-blank',
          isTextarea: false,
        },
      ],
    },
  ],
}
