import type { Quiz } from '@/lib/types/quiz'

export const quiz: Quiz = {
  id: 'quiz-lesson-2',
  lessonSlug: 'lesson-2',
  title: 'Lesson 2 Questions - The Pillars of Islam',
  sections: [
    {
      title: 'Tawheed Questions',
      questions: [
        {
          id: 'q1',
          number: 1,
          text: 'How many levels does the religion have?',
          type: 'multiple-choice',
          options: [
            'Three',
            'Four.',
            'Five.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q2',
          number: 2,
          text: 'How many pillars does Islam have?',
          type: 'multiple-choice',
          options: [
            'Five.',
            'Six.',
            'Seven.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q3',
          number: 3,
          text: 'Islam is a pillar which is higher than Emaan. ( True - False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'q4',
          number: 4,
          text: 'How many pillars does "La ilaha ila Allah" have?',
          type: 'multiple-choice',
          options: [
            'Seven.',
            'Eight.',
            'Two.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q5',
          number: 5,
          text: 'How many conditions does "La Ilaha ila Allah" have?',
          type: 'multiple-choice',
          options: [
            'Eight.',
            'Seven.',
            'Five.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q6',
          number: 6,
          text: 'Knowledge is from the conditions of "La ilaha ila Allah" and its meaning is:',
          type: 'multiple-choice',
          options: [
            'To understand the reality of something.',
            'There is none that deserves to be worshipped except Allah.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q7',
          number: 7,
          text: 'If one doubts in the disbelief of the one who has heard about Islam and yet has not become a Muslim\u2026',
          type: 'multiple-choice',
          options: [
            'S/he is no longer a Muslim.',
            'If their certainty is greater than their doubt, then they do not disbelieve.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q8',
          number: 8,
          text: 'Acceptance is from the conditions of "La ilaha ila Allah". It means',
          type: 'multiple-choice',
          options: [
            'accepting the statement.',
            'acting upon it.',
            'believing it.',
            'all of the above.',
          ],
          correctIndex: 3,
        },
        {
          id: 'q9',
          number: 9,
          text: 'Showing off with "La ilaha ila Allah" such as showing off while giving charity is Minor Shirk ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q10',
          number: 10,
          text: 'Whoever says "La ilaha ila Allah" without believing in it with his heart is\u2026',
          type: 'multiple-choice',
          options: [
            'believer.',
            'Muslim but not a believer.',
            'disbeliever.',
            'deficient in Emaan.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q11',
          number: 11,
          text: 'If one loves the Prophet the exact way one loves Allah; equal love:',
          type: 'multiple-choice',
          options: [
            'Major Disbelief.',
            'Minor Disbelief.',
            'Major Sin.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q12',
          number: 12,
          text: 'Love is divided in how many categories?',
          type: 'multiple-choice',
          options: [
            'Four.',
            'Three.',
            'Two.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q13',
          number: 13,
          text: 'The love for the sake of Allah is for good deeds, the person doing them, times, and places ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q14',
          number: 14,
          text: 'The ruling of loving someone as one loves Allah is\u2026',
          type: 'multiple-choice',
          options: [
            'Minor Shirk.',
            'Obligatory.',
            'Major Shirk.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q15',
          number: 15,
          text: 'The ruling of loving for the sake of Allah is\u2026',
          type: 'multiple-choice',
          options: [
            'Permissible.',
            'Obligatory.',
            'Major Shirk.',
          ],
          correctIndex: 1,
        },
        {
          id: 'q16',
          number: 16,
          text: 'How many types of \u2018Uboodiyyah/ being a slave of Allah are there?',
          type: 'multiple-choice',
          options: [
            '2',
            '3',
            '4',
          ],
          correctIndex: 0,
        },
        {
          id: 'q17',
          number: 17,
          text: 'Every creation is a slave of Allah in terms of subjugation; even the non-Muslims ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q18',
          number: 18,
          text: 'If one says "La ilaha ila Allah" while s/he does not pray nor do they perform any other act of worship:',
          type: 'multiple-choice',
          options: [
            'It benefits them.',
            'It does not benefit them.',
          ],
          correctIndex: 1,
        },
        {
          id: 'q19',
          number: 19,
          text: '"His slave and messenger" in the shahadah: A slave who is not worshipped and a messenger who should not be rejected ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q20',
          number: 20,
          text: 'The testimony "Surely Muhammad is His slave and messenger"; obeying his orders, believing what he has said\u2026is considered:',
          type: 'multiple-choice',
          options: [
            'its meaning',
            'what it implies.',
          ],
          correctIndex: 1,
        },
        {
          id: 'q21',
          number: 21,
          text: 'Whoever directs any part of lordship to the Prophet \uFDFA, then they have not testified that he is a slave ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q22',
          number: 22,
          text: 'The most noble description of the Prophet \uFDFA is',
          type: 'multiple-choice',
          options: [
            'the messenger of Allah',
            'His slave and messenger.',
            'the seal of the prophets.',
          ],
          correctIndex: 1,
        },
        {
          id: 'q23',
          number: 23,
          text: '"Whoever introduces a new act of worship in Islam considering it to be good, then s/he has claimed surely Muhammad \uFDFA has betrayed the Message; since Allah says: "This day I have completed for you your religion". Thus, whatever was not part of the religion on that day will not be part of the religion today". This is the saying of:',
          type: 'multiple-choice',
          options: [
            'Ibn Taymiyyah',
            'Ibn Baaz',
            'Imam Malik',
          ],
          correctIndex: 2,
        },
        {
          id: 'q24',
          number: 24,
          text: 'The Prophet \uFDFA is from the descendants of prophet\u2026',
          type: 'multiple-choice',
          options: [
            'Is\'haaq',
            'Ismaa\'eel',
          ],
          correctIndex: 1,
        },
        {
          id: 'q25',
          number: 25,
          text: 'Fill in the blanks: The Prophet \uFDFA is born in the year \u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026.. in the city of \u2026\u2026\u2026\u2026\u2026\u2026 He lived for \u2026\u2026\u2026.years; \u2026\u2026\u2026\u2026\u2026\u2026.. years before becoming a prophet and \u2026\u2026\u2026..as a prophet and messenger. He was made a prophet with the verse \u2026\u2026\u2026\u2026\u2026\u2026 and a messenger with the saying of Allah \u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026.',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q26',
          number: 26,
          text: 'The Prophet \uFDFA was sent to:',
          type: 'multiple-choice',
          options: [
            'His people',
            'the people',
            'people and jinn.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q27',
          number: 27,
          text: 'Al Ma\'aarij is his \uFDFA journey from Makkah to Bayt al Maqdis ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'q28',
          number: 28,
          text: 'The Prophet \uFDFA migrated to\u2026',
          type: 'multiple-choice',
          options: [
            'Taaif',
            'Ethiopia',
            'Madinah',
            'All of the above.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q29',
          number: 29,
          text: 'What is the number of his \uFDFA main battles?',
          type: 'multiple-choice',
          options: [
            'one',
            'two',
            'three',
            'four',
            'seven.',
          ],
          correctIndex: 4,
        },
        {
          id: 'q30',
          number: 30,
          text: 'How many children did he \uFDFA have?',
          type: 'multiple-choice',
          options: [
            'three',
            'four',
            'seven.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q31',
          number: 31,
          text: 'The Prophet \uFDFA performed his farewell pilgrimage and this shows that he has performed hajj before that ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'q32',
          number: 32,
          text: 'Studying the Prophet\'s \uFDFA biography is\u2026',
          type: 'multiple-choice',
          options: [
            'obligatory',
            'recommended',
            'permissible.',
          ],
          correctIndex: 0,
        },
      ],
    },
  ],
}
