import type { Quiz } from '@/lib/types/quiz'

export const quiz: Quiz = {
  id: 'lesson-18',
  lessonSlug: 'lesson-18',
  title: 'Lesson 18 Questions - Preparing the Deceased for Burial and Funeral Prayer',
  sections: [
    {
      title: 'Manners and Etiquettes Questions',
      questions: [
        {
          id: 'l18-q1',
          number: 1,
          text: 'From the Muslim\'s manners is practicing the Islamic etiquettes',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q2',
          number: 2,
          text: 'My religion orders me to accompany the evil people and stay away from the righteous ones',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'l18-q3',
          number: 3,
          text: 'Islam has taught us to treat the maids and worker well',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q4',
          number: 4,
          text: 'It is okay to accompany those who harm others verbally and physically',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'l18-q5',
          number: 5,
          text: 'I enjoy cursing someone who curses me',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'l18-q6',
          number: 6,
          text: 'Islam has taught me to help the poor and the weak',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q7',
          number: 7,
          text: 'From the rights of a Muslim on another Muslim is to visit when sick and supplicate for them',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q8',
          number: 8,
          text: 'Trying to find out the neighbor\'s secrets is from the Islamic manners',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'l18-q9',
          number: 9,
          text: 'The most beloved people to Allah are the ones who are the most beneficial for the people',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q10',
          number: 10,
          text: 'The supplication for leaving the house is "In the Name of Allah we enter, in the Name of Allah we exit, and upon our Lord we fully rely"',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'l18-q11',
          number: 11,
          text: 'I say to the one who says "May Allah have mercy on you" upon hearing me praise and thank Allah after I sneeze, "May Allah guide you and rectify your affairs"',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q12',
          number: 12,
          text: 'Remembering Allah protects a Muslim and draws one closer to Allah',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q13',
          number: 13,
          text: 'What is the sign that you love your Muslim brother or sister?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'l18-q14',
          number: 14,
          text: 'From that which shows that one\'s Emaan is deficient is: Being jealous of your Muslim brother or sister',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q15',
          number: 15,
          text: 'What are some things you can do for the people to like you?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'l18-q16',
          number: 16,
          text: 'That which is prohibited from the intoxicants is alcohol',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'l18-q17',
          number: 17,
          text: 'It is disliked to blow on the food and drink',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q18',
          number: 18,
          text: 'It is recommended to lick the fingers after eating and before washing the hands',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q19',
          number: 19,
          text: 'Being balanced regarding eating, clothing, and looking good is the best way',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
      ],
    },
    {
      title: 'Funeral Questions',
      questions: [
        {
          id: 'l18-q20',
          number: 20,
          text: 'The most deserving of washing the deceased and leading the prayer is ……………. then……………… then……………. then…………….',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'l18-q21',
          number: 21,
          text: 'Paying the debt of the dead person is...',
          type: 'multiple-choice',
          options: ['a must', 'recommended', 'permissible'],
          correctIndex: 0,
        },
        {
          id: 'l18-q22',
          number: 22,
          text: 'The ruling on burying the deceased is\u2026',
          type: 'multiple-choice',
          options: ['recommended', 'a must', 'communal obligation'],
          correctIndex: 2,
        },
        {
          id: 'l18-q23',
          number: 23,
          text: 'The ruling on reminding the one dying to say "La Ilaha ilaa Allah" is',
          type: 'multiple-choice',
          options: ['a must', 'recommended', 'prohibited'],
          correctIndex: 1,
        },
        {
          id: 'l18-q24',
          number: 24,
          text: 'The ruling on watching the deceased being washed, if one is not one of the people washing him is\u2026',
          type: 'multiple-choice',
          options: ['prohibited', 'permissible', 'disliked'],
          correctIndex: 2,
        },
        {
          id: 'l18-q25',
          number: 25,
          text: 'The knots of the shroud are untied once a person is put in the grave',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'l18-q26',
          number: 26,
          text: 'The spouses should not wash one another since the contract of marriage ends with death',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'l18-q27',
          number: 27,
          text: 'Men and women can wash who is …………………………………….',
          type: 'fill-blank',
          isTextarea: false,
        },
        {
          id: 'l18-q28',
          number: 28,
          text: 'Whoever misses the funeral prayer can pray at the ………….as long as a period of ……………..has not passed.',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'l18-q29',
          number: 29,
          text: 'Crying for the deceased is permissible without any restrictions',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'l18-q30',
          number: 30,
          text: 'The deceased should be placed in the opening on the side of the grave facing the Qiblah',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
      ],
    },
  ],
}
