import type { Quiz } from '@/lib/types/quiz'

export const quiz: Quiz = {
  id: 'quiz-lesson-5',
  lessonSlug: 'lesson-5',
  title: 'Lesson 5 Questions - Ihsaan (Excellence in Worship)',
  sections: [
    {
      title: 'Tawheed Questions',
      questions: [
        {
          id: 'q33',
          number: 33,
          text: 'Fill in the blanks: Emaan in Islam means a statement with the ………….., belief in the ………….., actions with ……………., it increases with ………… …………, and it decreases with …………',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q34',
          number: 34,
          text: 'How many pillars does Emaan have?',
          type: 'multiple-choice',
          options: [
            'six',
            'five',
            'four.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q35',
          number: 35,
          text: 'Believing in Allah entails a number of things. How many are they?',
          type: 'multiple-choice',
          options: [
            'four',
            'three',
            'two',
          ],
          correctIndex: -1,
        },
        {
          id: 'q36',
          number: 36,
          text: 'The general proofs for the existence of Allah are…',
          type: 'multiple-choice',
          options: [
            'four',
            'countless',
          ],
          correctIndex: -1,
        },
        {
          id: 'q37',
          number: 37,
          text: 'Meekaa\'eel is the angel who is entrusted with rain ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q38',
          number: 38,
          text: 'People have hearts while the angels do not have hearts ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q39',
          number: 39,
          text: 'How many revealed books do we know by name?',
          type: 'multiple-choice',
          options: [
            'Six',
            'four',
            'seven',
            'many',
          ],
          correctIndex: -1,
        },
        {
          id: 'q40',
          number: 40,
          text: 'Allah has revealed a book to every prophet ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q41',
          number: 41,
          text: 'The first messenger is Adam \u2013 peace be upon him- ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q42',
          number: 42,
          text: 'Muhammad \uFDFA is a messenger and not a prophet ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q43',
          number: 43,
          text: 'How many are \'the most determined\' messengers?',
          type: 'multiple-choice',
          options: [
            'five',
            'four',
            'many',
          ],
          correctIndex: -1,
        },
        {
          id: 'q44',
          number: 44,
          text: 'Believing in the Last Day entails believing in everything that happens after death until the people are resurrected from their graves ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q45',
          number: 45,
          text: 'How many categories does the belief in the Qadr have?',
          type: 'multiple-choice',
          options: [
            'four',
            'five',
            'three',
          ],
          correctIndex: -1,
        },
        {
          id: 'q46',
          number: 46,
          text: 'Does Allah know something before it happens? ( Yes \u2013 No ).',
          type: 'multiple-choice',
          options: ['Yes', 'No'],
          correctIndex: -1,
        },
        {
          id: 'q47',
          number: 47,
          text: 'Does Allah know everything the people do? ( Yes \u2013 No ).',
          type: 'multiple-choice',
          options: ['Yes', 'No'],
          correctIndex: -1,
        },
        {
          id: 'q48',
          number: 48,
          text: 'The people have a choice and will to do whatever they want ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q49',
          number: 49,
          text: 'Are the actions of the people created? ( Yes \u2013 No ).',
          type: 'multiple-choice',
          options: ['Yes', 'No'],
          correctIndex: -1,
        },
        {
          id: 'q50',
          number: 50,
          text: 'Tawheed is divided into …',
          type: 'multiple-choice',
          options: [
            'two categories',
            'three categories',
            'there is no dispute about it',
          ],
          correctIndex: -1,
        },
        {
          id: 'q51',
          number: 51,
          text: 'Mention five differences between Major and Minor Shirk.',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q52',
          number: 52,
          text: 'Mention five examples of Major and Minor Shirk.',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q53',
          number: 53,
          text: 'Hypocrisy of the heart is Minor Shirk which does not take one out of Islam ( True \u2013 False ).',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q54',
          number: 54,
          text: 'Ihsaan comprises of…',
          type: 'multiple-choice',
          options: [
            'one pillar',
            'two pillars',
          ],
          correctIndex: -1,
        },
      ],
    },
  ],
}
