import type { Quiz } from '@/lib/types/quiz'

export const quiz: Quiz = {
  id: 'quiz-tafseer-ayatul-kursee',
  lessonSlug: 'lesson-1',
  title: 'Ayatul Kursee Quiz',
  sections: [
    {
      title: 'The Verse of the Kursee (Footstool) Questions',
      questions: [
        {
          id: 'q35',
          number: 35,
          text: 'The verse of the Kursee is called with this name since Kursee is mentioned in it',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q36',
          number: 36,
          text: 'What is the greatest verse in the Qur\'an?',
          type: 'multiple-choice',
          options: [
            'The verse of debts.',
            'The verse which mentions the ten commands.',
            'The verse of the Kursee.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q37',
          number: 37,
          text: 'The Qur\'an has great meanings',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 3,
        },
        {
          id: 'q38',
          number: 38,
          text: 'How many names of Allah are found in the verse of the Kursee?',
          type: 'multiple-choice',
          options: [
            'Five.',
            'Six.',
            'Seven.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q39',
          number: 39,
          text: 'The name of Allah "The Ever Living" shows perfection of…',
          type: 'multiple-choice',
          options: [
            'power.',
            'self.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q40',
          number: 40,
          text: 'The name of Allah "The All Sustaining" shows perfection of…',
          type: 'multiple-choice',
          options: [
            'power',
            'self.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q41',
          number: 41,
          text: 'If the two names of Allah, The Ever Living and The All Sustaining, are mentioned together, they show perfection of self and perfection of power',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q42',
          number: 42,
          text: 'The two names, The Ever Living and The All Sustaining, have been mentioned together in the Qur\'an in …',
          type: 'multiple-choice',
          options: [
            'three places.',
            'four places.',
            'two places.',
          ],
          correctIndex: 1,
        },
        {
          id: 'q43',
          number: 43,
          text: 'It is a must to negate the attributes Allah has negated for Himself or the Prophet –may Allah praise and send him peace- has negated for Him while affirming the opposite of that attribute which is perfect. Negating only does not show outmost perfection. For example, we negate for Allah slumber and sleep in order to affirm His perfect Life and Sustaining',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q44',
          number: 44,
          text: 'Allah does not allow anyone to intercede except for the one He loves and He does not love except the one who…',
          type: 'multiple-choice',
          options: [
            'worships Him alone.',
            'follows the messengers.',
            'All of the above.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q45',
          number: 45,
          text: 'That which Allah has taught his creations regarding His Law and that which takes place in the universe is…',
          type: 'multiple-choice',
          options: [
            'little.',
            'a lot.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q46',
          number: 46,
          text: '"He knows what is in front of them" means the present and the future while "and what is behind them" means the past',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q47',
          number: 47,
          text: 'Meaning of the name of Allah "The Most High" is',
          type: 'multiple-choice',
          options: [
            'He Himself',
            'His attributes',
            'the One who has overpowered all of the creations.',
            'All of the above.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q48',
          number: 48,
          text: 'Whoever reads it before going to sleep will have a protection from Allah and shaytaan cannot come close until the morning. What is it?',
          type: 'multiple-choice',
          options: [
            'The end of Surah Al Baqarah.',
            'The verse of the Footstool',
          ],
          correctIndex: 0,
        },
        {
          id: 'q49',
          number: 49,
          text: 'It is recommended to read the verse of the Footstool …',
          type: 'multiple-choice',
          options: [
            'after the obligatory prayers.',
            'before sleeping.',
            'in the morning and the evening.',
            'All of the above.',
          ],
          correctIndex: 0,
        },
      ],
    },
  ],
}
