import type { Quiz } from '@/lib/types/quiz'

export const quiz: Quiz = {
  id: 'quiz-lesson-1',
  lessonSlug: 'lesson-1',
  title: 'Lesson 1 Questions - Short Surahs',
  sections: [
    {
      title: 'Introduction and Tafseer Questions',
      questions: [
        {
          id: 'q1',
          number: 1,
          text: 'Who is the author of the book "The Important Lessons…"?',
          type: 'multiple-choice',
          options: [
            'Abdul-Azeez ibn Baz',
            'Muhammad ibn Uthaymeen',
            'Haytham Sarhaan',
          ],
          correctIndex: -1,
        },
        {
          id: 'q2',
          number: 2,
          text: 'Why do we study "The Important Lessons"?',
          type: 'multiple-choice',
          options: [
            'They are important',
            'The Scholars have advised to study it.',
            'These lessons contain important topics which the Muslim needs',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q3',
          number: 3,
          text: 'This book consist of :',
          type: 'multiple-choice',
          options: [
            'The state of the Muslim regarding the Qur\'an and Tawheed',
            'Prayer and Wudu',
            'Manners',
            'Warning against sins.',
            'Preparing the dead person',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q4',
          number: 4,
          text: 'The Muslim should begin learning how to read, memorizing, and learning the meaning of:',
          type: 'multiple-choice',
          options: [
            'Surah Al-Alaq.',
            'Surah Al Faatihah.',
            'Surah Al Ikhlaas.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q5',
          number: 5,
          text: 'People are divided in two extremes and the moderate way regarding reflecting on the Qur\'an and acting upon it',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q6',
          number: 6,
          text: 'Which book of Tafseer should a Muslim begin with?',
          type: 'multiple-choice',
          options: [
            'Ibn Katheer.',
            'As-Sa\'dee.',
            'Al Qurtubee.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q7',
          number: 7,
          text: 'Students should begin studying short explanations before long explanations',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q8',
          number: 8,
          text: 'Students should begin reading the explanation of Surahs which they enjoy reading over and over such as Surah Al Qasas, Maryam, and Al Kahf',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q9',
          number: 9,
          text: 'Students may listen to audio books explaining the Qur\'an, if reading is difficult for them',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q10',
          number: 10,
          text: 'The Prophet –may Allah praise and send him peace- discouraged from reading the Qur\'an without reflecting on its meaning',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al Faatihah Questions',
      questions: [
        {
          id: 'q11',
          number: 11,
          text: 'This Surah is given this name because it is surrounded with a fence which prevents anything to exit from it or to enter it',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q12',
          number: 12,
          text: 'It is named Surah Al Faatihah because…',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q13',
          number: 13,
          text: 'The different names of Surah Al Faatihah are:',
          type: 'multiple-choice',
          options: [
            'The mother of the Qur\'an.',
            'The seven often repeated verses.',
            'The cure',
            'The Prayer.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q14',
          number: 14,
          text: 'Seeking refuge in Allah is a must before reciting the Qur\'an, even though we are doing an act of worship. Why?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q15',
          number: 15,
          text: 'What is the meaning of the word \'Aoodhu\'?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q16',
          number: 16,
          text: 'Shaytaan is called \'rrajeem\' because…',
          type: 'multiple-choice',
          options: [
            'he is expelled from mercy.',
            'he is thrown with shooting stars.',
            'he throws desires and doubts at the children of Adam.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q17',
          number: 17,
          text: 'The preposition and the noun following it in \'Bismi-laahi\' are linked to a verb which comes after it and has not been mentioned',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q18',
          number: 18,
          text: 'Allah…',
          type: 'multiple-choice',
          options: [
            'is the One who is worshipped out of love and glorification.',
            'no one has ever been named with this name except Allah.',
            'it is a reference point for all the other names of Allah.',
            'is the greatest name of Allah according to some.',
            'The two first letters Alif and Laam are not erased when calling Him.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q19',
          number: 19,
          text: 'What is the difference between the two beautiful names of Allah: ArRahmaan and Ar-Raheem?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q20',
          number: 20,
          text: 'Allah\'s taking care of His creations is of two types. What are they?',
          type: 'multiple-choice',
          options: [
            'General and Specific.',
            'Unrestricted and Restricted.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q21',
          number: 21,
          text: 'Most of the Prophets\' supplications are using the name of Allah…',
          type: 'multiple-choice',
          options: [
            'Allah.',
            'Rabb.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q22',
          number: 22,
          text: 'The Day of the Deen is…',
          type: 'multiple-choice',
          options: [
            'The Day of Resurrection.',
            'The day people will be rewarded according to their actions.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q23',
          number: 23,
          text: '"Guide us to the Straight Path" is the most comprehensive and beneficial supplication',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q24',
          number: 24,
          text: 'The word Deen refers to:',
          type: 'multiple-choice',
          options: [
            'The reward.',
            'The deeds.',
            'Sometimes to the reward and sometimes to the deeds.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q25',
          number: 25,
          text: 'Mentioning "You" before "We worship" grammatically indicates…',
          type: 'multiple-choice',
          options: [
            'Restriction of worship for Him alone.',
            'Nothing.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q26',
          number: 26,
          text: 'Mentioning \'the worship\' before \'the seeking help\' is an example of mentioning…',
          type: 'multiple-choice',
          options: [
            'the general term before the example.',
            'His right over the right of His slave.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q27',
          number: 27,
          text: 'Why is the verse "You alone we worship" mentioned in plural?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q28',
          number: 28,
          text: 'Worship…',
          type: 'multiple-choice',
          options: [
            'is an indefinite noun used for everything which Allah loves and is pleased with from the deeds and statements; the apparent ones and the inner ones.',
            'is humbling one\'s self to Allah by doing that which He has ordered and abandoning that which He has forbidden out of love and glorification for Him.',
            'refers sometimes to the first and sometimes to the second definition.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q29',
          number: 29,
          text: 'The intended \'Guidance\' in Allah\'s saying "Guide us" is…',
          type: 'multiple-choice',
          options: [
            'showing us the right way.',
            'to bless us to accept the guidance.',
            'Both.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q30',
          number: 30,
          text: 'Those intended in the saying of Allah "The way of those You have blessed" are…',
          type: 'multiple-choice',
          options: [
            'every believer.',
            'those who Allah has blessed from the prophets, truthful, martyrs, and the righteous.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q31',
          number: 31,
          text: '"You alone we worship and You alone we ask for help" combines between the legislation and the pre-decree',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q32',
          number: 32,
          text: 'Which of the following consists of that which no other part of the Qur\'an consists of?',
          type: 'multiple-choice',
          options: [
            'Surah Al Faatihah.',
            'The verse of the Kursee.',
            'Surah Al-Ikhlaas.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q33',
          number: 33,
          text: 'The saying of Allah "Guide us to the straight path" includes…',
          type: 'multiple-choice',
          options: [
            'affirming the prophets.',
            'a criticism for all those who introduce new acts of worship',
            'All of the above',
          ],
          correctIndex: -1,
        },
        {
          id: 'q34',
          number: 34,
          text: 'The saying of Allah "King of the Day of Judgment" means that…',
          type: 'multiple-choice',
          options: [
            'the rewards will be just.',
            'the slave is the one who actually does the deeds and s/he is not forced.',
            'the rewards will be for the deeds only.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'The Verse of the Kursee (Footstool) Questions',
      questions: [
        {
          id: 'q35',
          number: 35,
          text: 'The verse of the Kursee is called with this name since Kursee is mentioned in it',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q36',
          number: 36,
          text: 'What is the greatest verse in the Qur\'an?',
          type: 'multiple-choice',
          options: [
            'The verse of debts.',
            'The verse which mentions the ten commands.',
            'The verse of the Kursee.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q37',
          number: 37,
          text: 'The Qur\'an has great meanings',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q38',
          number: 38,
          text: 'How many names of Allah are found in the verse of the Kursee?',
          type: 'multiple-choice',
          options: [
            'Five.',
            'Six.',
            'Seven.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q39',
          number: 39,
          text: 'The name of Allah "The Ever Living" shows perfection of…',
          type: 'multiple-choice',
          options: [
            'power.',
            'self.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q40',
          number: 40,
          text: 'The name of Allah "The All Sustaining" shows perfection of…',
          type: 'multiple-choice',
          options: [
            'power',
            'self.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q41',
          number: 41,
          text: 'If the two names of Allah, The Ever Living and The All Sustaining, are mentioned together, they show perfection of self and perfection of power',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q42',
          number: 42,
          text: 'The two names, The Ever Living and The All Sustaining, have been mentioned together in the Qur\'an in …',
          type: 'multiple-choice',
          options: [
            'three places.',
            'four places.',
            'two places.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q43',
          number: 43,
          text: 'It is a must to negate the attributes Allah has negated for Himself or the Prophet –may Allah praise and send him peace- has negated for Him while affirming the opposite of that attribute which is perfect. Negating only does not show outmost perfection. For example, we negate for Allah slumber and sleep in order to affirm His perfect Life and Sustaining',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q44',
          number: 44,
          text: 'Allah does not allow anyone to intercede except for the one He loves and He does not love except the one who…',
          type: 'multiple-choice',
          options: [
            'worships Him alone.',
            'follows the messengers.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q45',
          number: 45,
          text: 'That which Allah has taught his creations regarding His Law and that which takes place in the universe is…',
          type: 'multiple-choice',
          options: [
            'little.',
            'a lot.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q46',
          number: 46,
          text: '"He knows what is in front of them" means the present and the future while "and what is behind them" means the past',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q47',
          number: 47,
          text: 'Meaning of the name of Allah "The Most High" is',
          type: 'multiple-choice',
          options: [
            'He Himself',
            'His attributes',
            'the One who has overpowered all of the creations.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q48',
          number: 48,
          text: 'Whoever reads it before going to sleep will have a protection from Allah and shaytaan cannot come close until the morning. What is it?',
          type: 'multiple-choice',
          options: [
            'The end of Surah Al Baqarah.',
            'The verse of the Footstool',
          ],
          correctIndex: -1,
        },
        {
          id: 'q49',
          number: 49,
          text: 'It is recommended to read the verse of the Footstool …',
          type: 'multiple-choice',
          options: [
            'after the obligatory prayers.',
            'before sleeping.',
            'in the morning and the evening.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al Zalzalah Questions',
      questions: [
        {
          id: 'q50',
          number: 50,
          text: 'Surah Zalzala is a…',
          type: 'multiple-choice',
          options: [
            'Maki Surah.',
            'Madani Surah.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q51',
          number: 51,
          text: 'Surah Zalzalah consists of…',
          type: 'multiple-choice',
          options: [
            'warning',
            'encouraging.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q52',
          number: 52,
          text: 'The saying of Allah "And when the earth throws out all its contents" means:',
          type: 'multiple-choice',
          options: [
            'Mountains and hills.',
            'The dead and treasures.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q53',
          number: 53,
          text: 'Earth is from among the witnesses which will bear witness for the people\'s actions',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q54',
          number: 54,
          text: 'The saying of Allah "in scattered groups" means…',
          type: 'multiple-choice',
          options: [
            'everyone by itself.',
            'different groups.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q55',
          number: 55,
          text: 'The saying of Allah "Whoever does an atom\'s weight of good will see it…" is similar to His saying "On the Day that each self finds the good it did, and the evil it did, present there in front of it…"',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al Aadiyaat Questions',
      questions: [
        {
          id: 'q56',
          number: 56,
          text: 'Surah Al Aadiyaat is a …',
          type: 'multiple-choice',
          options: [
            'Maki Surah.',
            'Madani Surah.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q57',
          number: 57,
          text: 'The meaning of the word \'\'Aadiyaat\'\' is…',
          type: 'multiple-choice',
          options: [
            'horses.',
            'everything which moves.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q58',
          number: 58,
          text: 'Surah Al Aadiyaat consists of warning for not performing the obligatory rights',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q59',
          number: 59,
          text: 'Explain the meaning of the following words:\nDab\'han:\nQad\'han:\nNaq\'an:\nLakanood:',
          type: 'fill-blank',
          isTextarea: true,
        },
      ],
    },
    {
      title: 'Surah Al Qaari\'ah Questions',
      questions: [
        {
          id: 'q60',
          number: 60,
          text: 'Surah Al Qaari\'ah is a…',
          type: 'multiple-choice',
          options: [
            'Maki Surah.',
            'Madani Surah.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q61',
          number: 61,
          text: 'From the goals of Surah Al Qaari\'ah is warning from:',
          type: 'multiple-choice',
          options: [
            'the shock of the Day of Judgement',
            'trials of this life.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q62',
          number: 62,
          text: 'Al Qaari\'ah is…',
          type: 'multiple-choice',
          options: [
            'the verses of warning.',
            'the Day of Judgement.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q63',
          number: 63,
          text: 'Explain the meaning of the following phrases:\n"like scattered moths"\n"like carded wool"',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q64',
          number: 64,
          text: 'The Scale mentioned in this Surah is…',
          type: 'multiple-choice',
          options: [
            'an actual Scale.',
            'a metaphor for justice.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q65',
          number: 65,
          text: '"a good life" meaning in…',
          type: 'multiple-choice',
          options: [
            'this life.',
            'Paradise.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q66',
          number: 66,
          text: '"his mother will be Hell" means:',
          type: 'multiple-choice',
          options: [
            'the fire will accompany him like the mother accompanies her child.',
            'the thin layer of skin surrounding the brain will burn in the fire.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q67',
          number: 67,
          text: 'The saying of Allah "What will make you realize what it is?!" …',
          type: 'multiple-choice',
          options: [
            'magnifies its reality.',
            'asks about it.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q68',
          number: 68,
          text: 'From the names of the Fire –may Allah protect us from it- are:',
          type: 'multiple-choice',
          options: [
            'Al Haawiyah.',
            'Jahannam.',
            'Al Hutamah.',
            'Ladha.',
            'Sa\'eer.',
            'Saqar.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q69',
          number: 69,
          text: '"a hot blazing Fire" –may Allah protect us from it- is ________ times more intense than the fire of this world',
          type: 'multiple-choice',
          options: [
            'seventy.',
            'ninety.',
            'ninety-nine.',
          ],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah At-Takaathur Questions',
      questions: [
        {
          id: 'q70',
          number: 70,
          text: 'This Surah is...',
          type: 'multiple-choice',
          options: [
            'Maki Surah.',
            'Madani Surah.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q71',
          number: 71,
          text: 'This Surah contains…',
          type: 'multiple-choice',
          options: [
            'news regarding the people\'s situation.',
            'criticism of the people for being preoccupied with other than what they were created for.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q72',
          number: 72,
          text: 'This Surah prohibits competition for more gains even if it is done for the sake of Allah',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q73',
          number: 73,
          text: 'The statement when someone dies: "S/he has moved on to the final abode" is…',
          type: 'multiple-choice',
          options: [
            'a rejection of the resurrection',
            'permissible',
          ],
          correctIndex: -1,
        },
        {
          id: 'q74',
          number: 74,
          text: 'In His saying "Until you visit", Allah has called them visitors and did not call them residents. Why?',
          type: 'multiple-choice',
          options: [
            'Since the life of the grave is a place which is meant to be a door to the next life',
            'Since they went from their house to the grave and it does not belong to them',
          ],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al \'Asr Questions',
      questions: [
        {
          id: 'q75',
          number: 75,
          text: 'Surah Al \'Asr is a…',
          type: 'multiple-choice',
          options: [
            'Maki Surah',
            'Madani Surah',
          ],
          correctIndex: -1,
        },
        {
          id: 'q76',
          number: 76,
          text: 'Surah Al \'Asr is a proof for seeking knowledge, acting upon it, teaching it, and patience',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q77',
          number: 77,
          text: 'Which of the following statements are correct regarding taking an oath in other than Allah:',
          type: 'multiple-choice',
          options: [
            'Allah may take an oath in anything He wishes from His creations.',
            'It is not permissible for the created beings to take an oath in other than Allah.',
            'Created beings may take an oath in other than Allah.',
            'The first and second answer.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q78',
          number: 78,
          text: 'Patience is divided into…',
          type: 'multiple-choice',
          options: [
            'Two categories.',
            'Three categories.',
            'Four categories',
          ],
          correctIndex: -1,
        },
        {
          id: 'q79',
          number: 79,
          text: 'The Surah consists of four orders: The first two help the person to improve himself while the second two help one improve others',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Humazah Questions',
      questions: [
        {
          id: 'q80',
          number: 80,
          text: 'This Surah is…',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q81',
          number: 81,
          text: 'The meaning of the word \'\'Wayl\'\' is…',
          type: 'multiple-choice',
          options: [
            'a \'valley\' in the Fire.',
            'a warning which includes a valley in the Fire and other than it.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q82',
          number: 82,
          text: 'Al Hamz is done by speech while Al-Lamz is done by gestures',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q83',
          number: 83,
          text: 'We benefit from the saying of Allah \'\'Thinking that wealth will make them last forever!\'\' that doing righteous deeds increases one\'s life span',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q84',
          number: 84,
          text: 'The meaning of the saying of Allah "And what will make you understand" is that…',
          type: 'multiple-choice',
          options: [
            'he knew about it',
            'he did not know about it',
          ],
          correctIndex: -1,
        },
        {
          id: 'q85',
          number: 85,
          text: 'In the saying of Allah, the Most High, \'\'It is Allah\'s kindled Fire\'\', that which will keep the fire going is…',
          type: 'multiple-choice',
          options: [
            'people.',
            'stones.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q86',
          number: 86,
          text: 'The saying of Allah, the Most High, "which rages over the hearts" means:',
          type: 'multiple-choice',
          options: [
            'due to that which it believes.',
            'It penetrates through the body to the heart.',
          ],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah of the The Elephant Questions',
      questions: [
        {
          id: 'q87',
          number: 87,
          text: 'The surah of "The Elephant" is …',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q88',
          number: 88,
          text: 'From the benefits of this surah is also the fact that the biggest living creature on land fears to transgress against a house from the houses of Allah. So the people should likewise fear',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q89',
          number: 89,
          text: 'The Prophet \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645 was born on the year of …',
          type: 'multiple-choice',
          options: [
            'the elephant',
            'the sadness.',
            'the drought.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q90',
          number: 90,
          text: 'This Surah is from the events and a miracle that happened prior to the prophethood of our Prophet –may Allah praise and send him peace-',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q91',
          number: 91,
          text: 'Mention the meaning of the following phrases:\n"Tayran abaabeel"\n"Ka\'asfin ma\'kool"',
          type: 'fill-blank',
          isTextarea: true,
        },
      ],
    },
    {
      title: 'Surah Quraysh Questions',
      questions: [
        {
          id: 'q92',
          number: 92,
          text: 'Surah Quraysh is…',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q93',
          number: 93,
          text: 'This Surah is closely related to Surah…',
          type: 'multiple-choice',
          options: [
            'Al Kaafiroon.',
            'Al Feel.',
            'An-Naas.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q94',
          number: 94,
          text: 'Quraysh used to travel to Shaam in the winter and to Yemen in the summer',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q95',
          number: 95,
          text: 'Allah has made Makkah great in the hearts of the Arabs so they respected them and they would not harm them…',
          type: 'multiple-choice',
          options: [
            'in Makkah.',
            'in Makkah and while traveling.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q96',
          number: 96,
          text: 'Allah has mentioned that He is the Lord of the House to show its virtue and status; even though, He is the Lord of everything',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al Maa\'oon Questions',
      questions: [
        {
          id: 'q97',
          number: 97,
          text: 'Surah Al Maa\'oon is …',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q98',
          number: 98,
          text: 'The meaning of the word \'deen\' in the saying of Allah "Have you seen the one who denies the deen" is…',
          type: 'multiple-choice',
          options: [
            'Resurrection and Recompense.',
            'others rights such as paying back the loan.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q99',
          number: 99,
          text: 'The meaning of the word \'yada\'u\' is to…',
          type: 'multiple-choice',
          options: [
            'abandon.',
            'harshly push away.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q100',
          number: 100,
          text: 'The orphan is the one who\'s ________ dies.',
          type: 'multiple-choice',
          options: [
            'father.',
            'mother.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q101',
          number: 101,
          text: 'The orphan is considered an orphan …',
          type: 'multiple-choice',
          options: [
            'as long as one has not reached puberty.',
            'even after puberty.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q102',
          number: 102,
          text: 'The forgetfulness in the prayer is the forgetfulness which is blameworthy; as for the negligence regarding the prayer, then that happens to everyone',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q103',
          number: 103,
          text: 'The ruling of showing off is …',
          type: 'multiple-choice',
          options: [
            'permissible.',
            'disliked.',
            'prohibited.',
            'minor shirk.',
            'major shirk.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q104',
          number: 104,
          text: 'This Surah encourages to help others',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q105',
          number: 105,
          text: 'Al Maa\'oon mentioned in the verse is…',
          type: 'multiple-choice',
          options: [
            'the dish.',
            'everything which is customary to spend and donate.',
          ],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al Kawthar Questions',
      questions: [
        {
          id: 'q106',
          number: 106,
          text: 'Surah AL Kawthar is...',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q107',
          number: 107,
          text: 'Al Kawthar is…',
          type: 'multiple-choice',
          options: [
            'a river.',
            'abundance of good and virtue.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q108',
          number: 108,
          text: 'Allah has specifically mentioned these two acts of worship, prayer and sacrificing animals, since they are the best acts of worship one can get closer to Allah with',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q109',
          number: 109,
          text: '\'Shaaniaka\' means…',
          type: 'multiple-choice',
          options: [
            'the one who hates you.',
            'the one who criticizes you.',
            'the one who takes away from your rights.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q110',
          number: 110,
          text: 'The saying of Allah "…is truly cut off from any goodness" indirectly proves that the one who loves the Prophet – may Allah praise and send him peace- will always be remembered and praised',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q111',
          number: 111,
          text: 'This Surah shows that the Prophet \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645 will have a lot of supporters and followers',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al Kaafiroon Questions',
      questions: [
        {
          id: 'q112',
          number: 112,
          text: 'Surah Al Kaafiroon is...',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q113',
          number: 113,
          text: 'Surah Al Kaafiroon is read in the first rak\'ah after Al Faatihah in…',
          type: 'multiple-choice',
          options: [
            'the Sunnah before Fajr.',
            'the Sunnah after Maghrib.',
            'the Sunnah after Tawaaf.',
            'the Witr prayer.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q114',
          number: 114,
          text: 'An act of worship which is done for other than Allah…',
          type: 'multiple-choice',
          options: [
            'is not considered worship.',
            'is a deficient worship.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q115',
          number: 115,
          text: 'The one being addressed with \'\'Say\'\' is…',
          type: 'multiple-choice',
          options: [
            'the Prophet \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645.',
            'the Prophet \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645 and everyone who could possibly be addressed with the similar words.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q116',
          number: 116,
          text: 'Kaafiroon are…',
          type: 'multiple-choice',
          options: [
            'all those whom the religion of our Prophet \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645 has reached them and have not believed in it such as the Jews and the Christians.',
            'the Non-Muslims of Makkah.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q117',
          number: 117,
          text: 'This Surah proves that we must stay far away from worshiping other than Allah and free ourselves from those who worship other than Allah with our heart, tongue, and limbs',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q118',
          number: 118,
          text: 'Repetition in this Surah…',
          type: 'multiple-choice',
          options: [
            'is for emphasis.',
            'Is to show that the first one proves the non-existence of the action while the second one proves that it has become an attribute of theirs.',
          ],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah An-Nasr Questions',
      questions: [
        {
          id: 'q119',
          number: 119,
          text: 'Surah An-Nasr is…',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q120',
          number: 120,
          text: 'This Surah contains a glad tiding, a news, a command, and a hint',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q121',
          number: 121,
          text: 'Allah has treated this nation and this religion with mercy and kindness that cannot be imagined and is beyond comprehension',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q122',
          number: 122,
          text: 'There is an indication in this Surah that the Prophet \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645 will pass away after a short period of time',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q123',
          number: 123,
          text: 'Acting upon this Surah, the Prophet \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645 used to often recite on the bowing position and prostration "You are Perfect O Allah, our Lord, O Allah forgive me"',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al-Masad Questions',
      questions: [
        {
          id: 'q124',
          number: 124,
          text: 'Surah Al Masad is…',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q125',
          number: 125,
          text: 'Aboo Lahab …',
          type: 'multiple-choice',
          options: [
            'is the Prophet\'s \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645 uncle.',
            'is not related to the Prophet \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q126',
          number: 126,
          text: 'Dispraised until the Day of Judgment is…',
          type: 'multiple-choice',
          options: [
            'Aboo Lahab.',
            'everyone who hates the Prophet \u0635\u0644\u0649 \u0627\u0644\u0644\u0647 \u0639\u0644\u064A\u0647 \u0648\u0633\u0644\u0645.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q127',
          number: 127,
          text: 'Mention the meaning of the following words:\n\u062A\u0651\u0628\u062A (Tabbat):\n\u0645\u0627 \u0643\u0633\u0628 (Maa-Kasaba):\n\u062C\u064A\u062F\u0647\u0627 (Jeedihaa):\n\u0645\u0633\u062F (Masad):',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q128',
          number: 128,
          text: 'This Surah contains an amazing miracle from the miracles of Allah with Aboo Lahab and his wife; they did not accept Islam!',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al-Ikhlaas Questions',
      questions: [
        {
          id: 'q129',
          number: 129,
          text: 'Surah Al-Ikhlaas is …',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q130',
          number: 130,
          text: 'Surah Al-Ikhlaas is called with this name since…',
          type: 'multiple-choice',
          options: [
            'all of it is a description of Allah',
            'it purifies those who read it from worshipping other than Allah',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q131',
          number: 131,
          text: 'This Surah is equal in reward to…',
          type: 'multiple-choice',
          options: [
            'half of the Qur\'an.',
            'quarter of the Qur\'an',
            'third of the Qur\'an.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q132',
          number: 132,
          text: 'This Surah is read in the second unit after Al Faatihah in the following prayers:',
          type: 'multiple-choice',
          options: [
            'the Sunnah before Fajr.',
            'the Sunnah after Maghrib.',
            'the Sunnah after Tawaaf.',
            'Witr prayer.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q133',
          number: 133,
          text: 'It is recommended to recite Surah Al Kaafiroon and Al Ikhlass during the day and night in order to affirm the three categories of Tawheed',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q134',
          number: 134,
          text: 'Surah Al Ikhlaas consist of…',
          type: 'multiple-choice',
          options: [
            'Tawheed of worship.',
            'Tawheed of Lordship and the Names and Attributes.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q135',
          number: 135,
          text: 'The meaning of "Say" is…',
          type: 'multiple-choice',
          options: [
            'make a statement only.',
            'a statement, actions, and belief.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q136',
          number: 136,
          text: 'The saying of Allah "He is Allah, the One and only" means One in His Lordship, Worship, and Names and Attributes',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
        {
          id: 'q137',
          number: 137,
          text: 'The saying of Allah "Allah, the Everlasting Sustainer of all" means…',
          type: 'multiple-choice',
          options: [
            'the One everyone turns to for all of their needs.',
            'the One Who is Self Sufficient and the Sustainer of All.',
            'the Master who is complete in His dominion, Lordship, Worship, and His Names and Attributes.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q138',
          number: 138,
          text: 'To attribute a child or parents to Allah is Major Disbelief',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah Al Falaq Questions',
      questions: [
        {
          id: 'q139',
          number: 139,
          text: 'Surah Al Falaq is…',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q140',
          number: 140,
          text: 'It is recommended to read Surah Al Falaq…',
          type: 'multiple-choice',
          options: [
            'after the obligatory prayers.',
            'just before sleep.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q141',
          number: 141,
          text: 'Write the meaning of the following words:\n\u0623\u0639\u0648\u0630 (Aoodhu\'):\n\u0627\u0644\u0641\u0644\u0642 (Al Falaq):\n\u063A\u0627\u0633\u0650\u0642 (Ghaasiq):\n\u0648\u0642\u0650\u0628 (waqab):\n\u0627\u0644\u0646\u0651\u064E\u0641\u0651\u0627\u062B\u0627\u062A (An-Naffathaat):\n\u0627\u0644\u0639\u064F\u0642\u064E\u062F (Al\'Uqad):\n\u062D\u0627\u0633\u0650\u062F (Haasidin):',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q142',
          number: 142,
          text: 'This Surah shows that…',
          type: 'multiple-choice',
          options: [
            'seeking refuge is done in general as well as specific.',
            'magic is real.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
      ],
    },
    {
      title: 'Surah An-Naas Questions',
      questions: [
        {
          id: 'q143',
          number: 143,
          text: 'Surah An-Naas is…',
          type: 'multiple-choice',
          options: [
            'Maki.',
            'Madani.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q144',
          number: 144,
          text: 'It is recommended to read Surah Al-Naas…',
          type: 'multiple-choice',
          options: [
            'after the obligatory prayers.',
            'just before sleeping.',
            'All of the above.',
          ],
          correctIndex: -1,
        },
        {
          id: 'q145',
          number: 145,
          text: 'What is the meaning of the word \'Al Khannaas\'?',
          type: 'fill-blank',
          isTextarea: true,
        },
      ],
    },
  ],
}
