import type { Quiz } from '@/lib/types/quiz'

export const quiz: Quiz = {
  id: 'quiz-lesson-1',
  lessonSlug: 'lesson-1',
  title: 'Lesson 1 - Introduction',
  sections: [
    {
      title: 'Introduction and Tafseer Questions',
      questions: [
        {
          id: 'q1',
          number: 1,
          text: 'Who is the author of the book "The Important Lessons…"?',
          type: 'multiple-choice',
          options: [
            'Abdul-Azeez ibn Baz',
            'Muhammad ibn Uthaymeen',
            'Haytham Sarhaan',
          ],
          correctIndex: 0,
        },
        {
          id: 'q2',
          number: 2,
          text: 'Why do we study "The Important Lessons"?',
          type: 'multiple-choice',
          options: [
            'They are important',
            'The Scholars have advised to study it.',
            'These lessons contain important topics which the Muslim needs',
            'All of the above.',
          ],
          correctIndex: 3,
        },
        {
          id: 'q3',
          number: 3,
          text: 'This book consist of :',
          type: 'multiple-choice',
          options: [
            'The state of the Muslim regarding the Qur\'an and Tawheed',
            'Prayer and Wudu',
            'Manners',
            'Warning against sins.',
            'Preparing the dead person',
            'All of the above.',
          ],
          correctIndex: 5,
        },
        {
          id: 'q4',
          number: 4,
          text: 'The Muslim should begin learning how to read, memorizing, and learning the meaning of:',
          type: 'multiple-choice',
          options: [
            'Surah Al-Alaq.',
            'Surah Al Faatihah.',
            'Surah Al Ikhlaas.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q5',
          number: 5,
          text: 'People are divided in two extremes and the moderate way regarding reflecting on the Qur\'an and acting upon it',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 3,
        },
        {
          id: 'q6',
          number: 6,
          text: 'Which book of Tafseer should a Muslim begin with?',
          type: 'multiple-choice',
          options: [
            'Ibn Katheer.',
            'As-Sa\'dee.',
            'Al Qurtubee.',
          ],
          correctIndex: 5,
        },
        {
          id: 'q7',
          number: 7,
          text: 'Students should begin studying short explanations before long explanations',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'q8',
          number: 8,
          text: 'Students should begin reading the explanation of Surahs which they enjoy reading over and over such as Surah Al Qasas, Maryam, and Al Kahf',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q9',
          number: 9,
          text: 'Students may listen to audio books explaining the Qur\'an, if reading is difficult for them',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'q10',
          number: 10,
          text: 'The Prophet –may Allah praise and send him peace- discouraged from reading the Qur\'an without reflecting on its meaning',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
      ],
    },
  ],
}
