import type { Quiz } from '@/lib/types/quiz'

export const quiz: Quiz = {
  id: 'quiz-tafseer-al-faatiha',
  lessonSlug: 'lesson-1',
  title: 'Surah Al Faatihah Quiz',
  sections: [
    {
      title: 'Surah Al Faatihah Questions',
      questions: [
        {
          id: 'q11',
          number: 11,
          text: 'This Surah is given this name because it is surrounded with a fence which prevents anything to exit from it or to enter it',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q12',
          number: 12,
          text: 'It is named Surah Al Faatihah because…',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q13',
          number: 13,
          text: 'The different names of Surah Al Faatihah are:',
          type: 'multiple-choice',
          options: [
            'The mother of the Qur\'an.',
            'The seven often repeated verses.',
            'The cure',
            'The Prayer.',
            'All of the above.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q14',
          number: 14,
          text: 'Seeking refuge in Allah is a must before reciting the Qur\'an, even though we are doing an act of worship. Why?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q15',
          number: 15,
          text: 'What is the meaning of the word \'Aoodhu\'?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q16',
          number: 16,
          text: 'Shaytaan is called \'rrajeem\' because…',
          type: 'multiple-choice',
          options: [
            'he is expelled from mercy.',
            'he is thrown with shooting stars.',
            'he throws desires and doubts at the children of Adam.',
            'All of the above.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q17',
          number: 17,
          text: 'The preposition and the noun following it in \'Bismi-laahi\' are linked to a verb which comes after it and has not been mentioned',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 1,
        },
        {
          id: 'q18',
          number: 18,
          text: 'Allah…',
          type: 'multiple-choice',
          options: [
            'is the One who is worshipped out of love and glorification.',
            'no one has ever been named with this name except Allah.',
            'it is a reference point for all the other names of Allah.',
            'is the greatest name of Allah according to some.',
            'The two first letters Alif and Laam are not erased when calling Him.',
            'All of the above.',
          ],
          correctIndex: 4,
        },
        {
          id: 'q19',
          number: 19,
          text: 'What is the difference between the two beautiful names of Allah: ArRahmaan and Ar-Raheem?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q20',
          number: 20,
          text: 'Allah\'s taking care of His creations is of two types. What are they?',
          type: 'multiple-choice',
          options: [
            'General and Specific.',
            'Unrestricted and Restricted.',
          ],
          correctIndex: 3,
        },
        {
          id: 'q21',
          number: 21,
          text: 'Most of the Prophets\' supplications are using the name of Allah…',
          type: 'multiple-choice',
          options: [
            'Allah.',
            'Rabb.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q22',
          number: 22,
          text: 'The Day of the Deen is…',
          type: 'multiple-choice',
          options: [
            'The Day of Resurrection.',
            'The day people will be rewarded according to their actions.',
            'All of the above.',
          ],
          correctIndex: 5,
        },
        {
          id: 'q23',
          number: 23,
          text: '"Guide us to the Straight Path" is the most comprehensive and beneficial supplication',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 0,
        },
        {
          id: 'q24',
          number: 24,
          text: 'The word Deen refers to:',
          type: 'multiple-choice',
          options: [
            'The reward.',
            'The deeds.',
            'Sometimes to the reward and sometimes to the deeds.',
          ],
          correctIndex: 1,
        },
        {
          id: 'q25',
          number: 25,
          text: 'Mentioning "You" before "We worship" grammatically indicates…',
          type: 'multiple-choice',
          options: [
            'Restriction of worship for Him alone.',
            'Nothing.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q26',
          number: 26,
          text: 'Mentioning \'the worship\' before \'the seeking help\' is an example of mentioning…',
          type: 'multiple-choice',
          options: [
            'the general term before the example.',
            'His right over the right of His slave.',
            'All of the above.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q27',
          number: 27,
          text: 'Why is the verse "You alone we worship" mentioned in plural?',
          type: 'fill-blank',
          isTextarea: true,
        },
        {
          id: 'q28',
          number: 28,
          text: 'Worship…',
          type: 'multiple-choice',
          options: [
            'is an indefinite noun used for everything which Allah loves and is pleased with from the deeds and statements; the apparent ones and the inner ones.',
            'is humbling one\'s self to Allah by doing that which He has ordered and abandoning that which He has forbidden out of love and glorification for Him.',
            'refers sometimes to the first and sometimes to the second definition.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q29',
          number: 29,
          text: 'The intended \'Guidance\' in Allah\'s saying "Guide us" is…',
          type: 'multiple-choice',
          options: [
            'showing us the right way.',
            'to bless us to accept the guidance.',
            'Both.',
          ],
          correctIndex: 0,
        },
        {
          id: 'q30',
          number: 30,
          text: 'Those intended in the saying of Allah "The way of those You have blessed" are…',
          type: 'multiple-choice',
          options: [
            'every believer.',
            'those who Allah has blessed from the prophets, truthful, martyrs, and the righteous.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q31',
          number: 31,
          text: '"You alone we worship and You alone we ask for help" combines between the legislation and the pre-decree',
          type: 'true-false',
          options: ['True', 'False'],
          correctIndex: 2,
        },
        {
          id: 'q32',
          number: 32,
          text: 'Which of the following consists of that which no other part of the Qur\'an consists of?',
          type: 'multiple-choice',
          options: [
            'Surah Al Faatihah.',
            'The verse of the Kursee.',
            'Surah Al-Ikhlaas.',
          ],
          correctIndex: 2,
        },
        {
          id: 'q33',
          number: 33,
          text: 'The saying of Allah "Guide us to the straight path" includes…',
          type: 'multiple-choice',
          options: [
            'affirming the prophets.',
            'a criticism for all those who introduce new acts of worship',
            'All of the above',
          ],
          correctIndex: 1,
        },
        {
          id: 'q34',
          number: 34,
          text: 'The saying of Allah "King of the Day of Judgment" means that…',
          type: 'multiple-choice',
          options: [
            'the rewards will be just.',
            'the slave is the one who actually does the deeds and s/he is not forced.',
            'the rewards will be for the deeds only.',
            'All of the above.',
          ],
          correctIndex: 0,
        },
      ],
    },
  ],
}
